# 本地环境
server:
  servlet:
    context-path: /
  port: 9998
spring:
  datasource:
    dynamic:
      enabled: true #启用动态数据源，默认true
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      grace-destroy: false #是否优雅关闭数据源，默认为false，设置为true时，关闭数据源时如果数据源中还存在活跃连接，至多等待10s后强制关闭
      datasource:
        master:
          url: jdbc:sqlite:sqlTools.db
          driver-class-name: org.sqlite.JDBC
          hikari:
            max-lifetime: 900000
            max-pool-size: 12
            connection-timeout: 30000
            idle-timeout: 600000

#公共文件的配置
# 上传的地址
public-file:
  uploadUrl: https://upload.qiniup.com
  domain: https://upload.qiniup.com

# 跨域设置
cors:
  allowed-origins: http://localhost:8080
  allowed-headers: Content-Type,X-Adminid,X-Token
  allowed-methods: GET,POST,OPTIONS

